const data = {
  dairy: [
    {
      name: 'Cream 36%',
      waterContent: 0.577,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0.366,
    },
    {
      name: 'Cream 40%',
      waterContent: 0.544,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0.4,
    },
  ],
  fats: [
    {
      name: 'Butter',
      waterContent: 0.18,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0.82,
    },
    {
      name: 'Clarified butter',
      waterContent: 0,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 1,
    },
    {
      name: 'Cocoa butter',
      waterContent: 0,
      sugarContent: 0,
      cocoaFatContent: 1,
      dairyFatContent: 0,
    },
  ],
  sugars: [
    {
      name: 'Granulated sugar',
      waterContent: 0,
      sugarContent: 1,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Glucose',
      waterContent: 0.22,
      sugarContent: 0.78,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Inverted sugar',
      waterContent: 0.18,
      sugarContent: 0.82,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
  ],
  fruits: [
    {
      name: 'Strawberry',
      waterContent: 0.92,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Grapefruit',
      waterContent: 0.91,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Peach',
      waterContent: 0.88,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Orange',
      waterContent: 0.87,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Pineapple',
      waterContent: 0.87,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Raspberry',
      waterContent: 0.87,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Apricot',
      waterContent: 0.86,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Blueberry',
      waterContent: 0.85,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Apple',
      waterContent: 0.84,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Pear',
      waterContent: 0.84,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Cherry',
      waterContent: 0.81,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
    {
      name: 'Banana',
      waterContent: 0.74,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
  ],
  chocolate: [
    {
      name: 'Callebaut 811 - 54,5%',
      waterContent: 0,
      sugarContent: 0.43,
      cocoaFatContent: 0.366,
      dairyFatContent: 0,
    },
    {
      name: 'Callebaut 823 - 38%',
      waterContent: 0,
      sugarContent: 0.5,
      cocoaFatContent: 0.362,
      dairyFatContent: 0,
    },
    {
      name: 'Callebaut W2 - 28%',
      waterContent: 0,
      sugarContent: 0.465,
      cocoaFatContent: 0.358,
      dairyFatContent: 0,
    },
  ],
  alcohol: [
    {
      name: 'Alcohol 40%',
      waterContent: 0.6,
      sugarContent: 0,
      cocoaFatContent: 0,
      dairyFatContent: 0,
    },
  ],
};

export default data;
